姓名:制造设备

 在…上  :
  工作流程  :
    投入  :
      img_url  :    
        描述  : 'IMG_URL'
        必需的  : 真实的
        违约  : ''

 乔布斯  :
  建造  :
    如果 :github.event.repository.owner.id == github.event.sender.id
    逃跑 :ubuntu-20.04
    
    台阶  :
    - 姓名:退房
      使用:行动/结账@主要
      
    - 姓名:准备环境
      跑  : |
        最新情况
        安装巨蛇天蛇3天蛇3天蛇3
        Pip3安饰Twrpdtkin
        Dt
      
    - 姓名:下载引导或恢复
      跑  : |
        aria2c "${{ github.event.inputs.IMG_URL }}"
        元素元素
      
    - 姓名:开始构建
      跑 : |
        python3 -m twrpdtgen -o dt/ *.img
    - name:     -名称:邮政设备树
      run: |
        zip -r DeviceTree.zip ./dt
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./DeviceTree.zip
        name: TWRP_Device_Tree-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: DeviceTree for twrp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
